#frontend
yaroslavche_sylius_translation_plugin_dashboard:
  path:     /admin/translation/
  controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::dashboard

# ajax
yaroslavche_sylius_translation_plugin_set_message:
  path:     /admin/translation/setMessage
  methods: ['POST']
  controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::setMessage

yaroslavche_sylius_translation_plugin_get_locales:
  path:     /admin/translation/getLocales
  methods: ['GET']
  controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::getLocales

yaroslavche_sylius_translation_plugin_get_message_catalogue:
  path:     /admin/translation/getMessageCatalogue
  methods: ['POST']
  controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::getMessageCatalogue

yaroslavche_sylius_translation_plugin_add_locale:
    path:     /admin/translation/addLocale
    methods: ['POST']
    controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::addLocale

yaroslavche_sylius_translation_plugin_remove_locale:
    path:     /admin/translation/removeLocale
    methods: ['POST']
    controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::removeLocale

yaroslavche_sylius_translation_plugin_add_domain:
  path:     /admin/translation/addDomain
  methods: ['POST']
  controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::addDomain
