#frontend
yaroslavche_sylius_translation_plugin_dashboard:
    path:     /admin/translation/
    controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::dashboard

yaroslavche_sylius_translation_plugin_locale:
    path:     /admin/translation/{localeCode}/{domain}
    controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::locale
    requirements:
        localeCode: '^[a-z]{2,3}(?:_[A-Z]{2})?$'
        domain: '.+'
    defaults:
        domain: ''


# ajax
yaroslavche_sylius_translation_plugin_set_message:
    path:     /admin/translation/setMessage
    methods: ['POST']
    controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::setMessage

yaroslavche_sylius_translation_plugin_add_domain:
    path:     /admin/translation/addDomain
    methods: ['POST']
    controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::addDomain

#yaroslavche_sylius_translation_plugin_add_locale:
#    path:     /admin/translation/addLocale
#    methods: ['POST']
#    controller: Yaroslavche\SyliusTranslationPlugin\Controller\TranslationController::addLocale
