services:
    # plugin service
    translation_plugin_service:
        class: Acme\SyliusTranslationPlugin\Service\TranslationPlugin
        calls:
            - [setContainer, ['@service_container']]
            - [init]

    # add menu via listener
    app.listener.admin.menu_builder:
        class: Acme\SyliusTranslationPlugin\Listener\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
