sylius_translation_plugin_dashboard:
    path: /admin/translation/
    defaults:
        _controller: AcmeSyliusTranslationPlugin:Translation:dashboard

sylius_translation_plugin_translation_set_message:
    path: /admin/translation/set
    defaults:
        _controller: AcmeSyliusTranslationPlugin:Translation:setMessage

sylius_translation_plugin_translation_locale:
    path: /admin/translation/{localeCode}
    defaults:
        _controller: AcmeSyliusTranslationPlugin:Translation:locale
    requirements:
        localeCode: '^(?!set)[a-z]{2,3}(?:_[A-Z]{2})?$'

sylius_translation_plugin_translation_locale_domain:
    path: /admin/translation/{localeCode}/{domain}
    defaults:
        _controller: AcmeSyliusTranslationPlugin:Translation:locale
    requirements:
        localeCode: '^(?!set)[a-z]{2,3}(?:_[A-Z]{2})?$'
        domain: '.+'
